// Generated by CoffeeScript 1.3.3
(function() {

  describe('Webdlmon', function() {});

  describe('Utils', function() {
    beforeEach(function() {
      var testdl;
      return testdl = new Webdlmon.Datalogger({
        "dlname": 'TA_246A',
        "aa": "0.009",
        "acok": "1",
        "api": "0",
        "br24": "52993057.0",
        "bw24": "967116.0",
        "cale": "-",
        "cals": "-",
        "ce": "88.406",
        "cld": "0",
        "clq": "l",
        "clt": "0.000",
        "con": "sleeping",
        "da": "0.068",
        "dbc": "0",
        "dbd": "0",
        "dbu": "0",
        "dg": "0.000",
        "dlt": "119.071",
        "dr": "70",
        "dt": "25.000",
        "dv": "12.000",
        "e1a140": "1.39e+06",
        "e1a240": "-3.96e+03",
        "e1bar": "1.39e+06",
        "e1ih": "16",
        "e1ipr": "1.01e+03",
        "e1it": "27.2",
        "e1iv": "11.2",
        "e1mic": "-3.11e+04",
        "e1pll": "5e-06",
        "e1vco": "-490",
        "elev": "0.1022",
        "gp1": "0.000",
        "gp24": "0.000",
        "gps": "elck 3d",
        "gpss": "-",
        "inp": "udp:166.186.86.12:5332:L1:startacq:0:0",
        "isp1": "1",
        "isp2": "0",
        "lat": "32.014378",
        "lcq": "100.000",
        "lon": "-89.128722",
        "m0": "-18",
        "m1": "18",
        "m2": "-6",
        "m3": "20",
        "m4": "20",
        "m5": "20",
        "meme": "0",
        "nc": "6",
        "ni24": "0.0",
        "nl24": "15.0",
        "np24": "10.0",
        "nr24": "0.0",
        "nrb": "268",
        "nrs": "302",
        "opt": "acok isp1 ti",
        "pb": "0.000",
        "pbr": "-",
        "pkce": "1",
        "pkp": "7455",
        "pkse": "0",
        "pt": "1108",
        "rtm": "-83.434",
        "sc0": "-",
        "sc1": "-",
        "sc2": "-",
        "sc3": "-",
        "sn": "0100000A1BA29B02",
        "thr": "56000",
        "ti": "1",
        "tput": "0.116",
        "trb": "1338944359",
        "trs": "1338944380",
        "vco": "2232"
      });
    });
    return describe("sortorder", function() {
      return describe("dlname", function() {
        return it("sorts dlname", function() {
          var sorted;
          sorted = Webdlmon.Utils.sortorder('dlname', testdl.toJSON);
          return (expect(sorted)).toEqual("1_TA_246A");
        });
      });
    });
  });

}).call(this);
